# scoreboard control
execute if entity @s[tag=trust_player_control] if score speed_run timer_settings matches 0 unless score speed_x timer_addon matches 1 unless score gravity timer_addon matches 1 run scoreboard players add afk timer_settings 1
execute if entity @s[tag=trust_player_control] if score speed_run timer_settings matches 0 unless score speed_x timer_addon matches 1 unless score gravity timer_addon matches 1 if score afk timer_settings matches 2.. run scoreboard players set afk timer_settings 0

# afk_disable message
execute if entity @s[tag=trust_player_control] if score speed_run timer_settings matches 0 unless score speed_x timer_addon matches 1 unless score gravity timer_addon matches 1 if score mode timer_settings matches 0..1 if score afk timer_settings matches 0 run title @s title §bAFK §7§o[BETA]
execute if entity @s[tag=trust_player_control] if score speed_run timer_settings matches 0 unless score speed_x timer_addon matches 1 unless score gravity timer_addon matches 1 if score mode timer_settings matches 0..1 if score afk timer_settings matches 0 run title @s subtitle -- is now §cdisabled§f --
execute if entity @s[tag=trust_player_control] if score speed_run timer_settings matches 0 unless score speed_x timer_addon matches 1 unless score gravity timer_addon matches 1 if score mode timer_settings matches 0..1 if score afk timer_settings matches 0 if score lang timer_settings matches 0 run tellraw @a[tag=trust_player_control] {"rawtext":[{"text":"§l§3[§bAFK§3]§r The automatic AFK detector is deactivated and the timer continues to run all the time."}]}
execute if entity @s[tag=trust_player_control] if score speed_run timer_settings matches 0 unless score speed_x timer_addon matches 1 unless score gravity timer_addon matches 1 if score mode timer_settings matches 0..1 if score afk timer_settings matches 0 if score lang timer_settings matches 1 run tellraw @a[tag=trust_player_control] {"rawtext":[{"text":"§l§3[§bAFK§3]§r Der automatische AFK-Detektor ist deaktiviert und der Timer läuft ständig weiter."}]}
execute if entity @s[tag=trust_player_control] if score speed_run timer_settings matches 0 unless score speed_x timer_addon matches 1 unless score gravity timer_addon matches 1 if score mode timer_settings matches 0..1 if score afk timer_settings matches 0 if score lang timer_settings matches 2 run tellraw @a[tag=trust_player_control] {"rawtext":[{"translate":"timeru.header.afk"},{"text":" "},{"translate":"timeru.message.afk.off"}]}
execute if entity @s[tag=trust_player_control] if score speed_run timer_settings matches 0 unless score speed_x timer_addon matches 1 unless score gravity timer_addon matches 1 if score mode timer_settings matches 0..1 if score afk timer_settings matches 0 unless score custom_music timer_settings matches 1 run playsound respawn_anchor.deplete @a[tag=trust_player_control]
execute if entity @s[tag=trust_player_control] if score speed_run timer_settings matches 0 unless score speed_x timer_addon matches 1 unless score gravity timer_addon matches 1 if score mode timer_settings matches 0..1 if score afk timer_settings matches 0 if score custom_music timer_settings matches 1 run playsound timeru.afk_0 @a[tag=trust_player_control]

# afk enable message 
execute if entity @s[tag=trust_player_control] if score speed_run timer_settings matches 0 unless score speed_x timer_addon matches 1 unless score gravity timer_addon matches 1 if score mode timer_settings matches 0..1 if score afk timer_settings matches 1 run title @s title §bAFK §7§o[BETA]
execute if entity @s[tag=trust_player_control] if score speed_run timer_settings matches 0 unless score speed_x timer_addon matches 1 unless score gravity timer_addon matches 1 if score mode timer_settings matches 0..1 if score afk timer_settings matches 1 run title @s subtitle -- is now §aactiv§f --
execute if entity @s[tag=trust_player_control] if score speed_run timer_settings matches 0 unless score speed_x timer_addon matches 1 unless score gravity timer_addon matches 1 if score mode timer_settings matches 0..1 if score afk timer_settings matches 1 if score lang timer_settings matches 0 run tellraw @a[tag=trust_player_control] {"rawtext":[{"text":"§l§3[§bAFK§3]§r The automatic AFK detector is activated, if someone goes AFK for more than 30 seconds, the timer will be paused."}]}
execute if entity @s[tag=trust_player_control] if score speed_run timer_settings matches 0 unless score speed_x timer_addon matches 1 unless score gravity timer_addon matches 1 if score mode timer_settings matches 0..1 if score afk timer_settings matches 1 if score lang timer_settings matches 1 run tellraw @a[tag=trust_player_control] {"rawtext":[{"text":"§l§3[§bAFK§3]§r Der automatische AFK-Detektor ist aktiviert. Wenn jemand länger als 30 Sekunden AFK bleibt, wird der Timer angehalten."}]}
execute if entity @s[tag=trust_player_control] if score speed_run timer_settings matches 0 unless score speed_x timer_addon matches 1 unless score gravity timer_addon matches 1 if score mode timer_settings matches 0..1 if score afk timer_settings matches 1 if score lang timer_settings matches 2 run tellraw @a[tag=trust_player_control] {"rawtext":[{"translate":"timeru.header.afk"},{"text":" "},{"translate":"timeru.message.afk.on"}]}
execute if entity @s[tag=trust_player_control] if score speed_run timer_settings matches 0 unless score speed_x timer_addon matches 1 unless score gravity timer_addon matches 1 if score mode timer_settings matches 0..1 if score afk timer_settings matches 1 unless score custom_music timer_settings matches 1 run playsound respawn_anchor.charge @a[tag=trust_player_control]
execute if entity @s[tag=trust_player_control] if score speed_run timer_settings matches 0 unless score speed_x timer_addon matches 1 unless score gravity timer_addon matches 1 if score mode timer_settings matches 0..1 if score afk timer_settings matches 1 if score custom_music timer_settings matches 1 run playsound timeru.afk_1 @a[tag=trust_player_control]

# Errors

# Incompatible challenges / Features
execute if entity @s[tag=trust_player_control] if score mode timer_settings matches 0..1 if score gravity timer_addon matches 1 if score lang timer_settings matches 0 run tellraw @s {"rawtext":[{"text":"§l§6[§eError§6]§r AFK isn't compatible with the Gravity Challenge! Disable the Gravity Challenge to make changes."}]}
execute if entity @s[tag=trust_player_control] if score mode timer_settings matches 0..1 if score gravity timer_addon matches 1 if score lang timer_settings matches 1 run tellraw @s {"rawtext":[{"text":"§l§6[§eError§6]§r AFK ist nicht mit dem Speed Run Mode kompatible! Deaktivieren sie die Gravity Challenge um Änderungen vorzunehmen."}]}
execute if entity @s[tag=trust_player_control] if score mode timer_settings matches 0..1 if score gravity timer_addon matches 1 if score lang timer_settings matches 2 run tellraw @s {"rawtext":[{"translate":"timeru.header.error"},{"text":" "},{"translate":"timeru.message.incompatible.not_possible", "with":["AFK"," Gravity"]}]}
execute if entity @s[tag=trust_player_control] if score mode timer_settings matches 0..1 if score gravity timer_addon matches 1 run title @a[tag=timer_menu_target] title §eAn Error occurred
execute if entity @s[tag=trust_player_control] if score mode timer_settings matches 0..1 if score gravity timer_addon matches 1 run title @a[tag=timer_menu_target] subtitle -- Look in the chat --
execute if entity @s[tag=trust_player_control] if score mode timer_settings matches 0..1 if score gravity timer_addon matches 1 unless score custom_music timer_settings matches 1 run playsound random.pop @s
execute if entity @s[tag=trust_player_control] if score mode timer_settings matches 0..1 if score gravity timer_addon matches 1 if score custom_music timer_settings matches 1 run playsound timeru.message @s

execute if entity @s[tag=trust_player_control] if score mode timer_settings matches 0..1 if score speed_x timer_addon matches 1 if score lang timer_settings matches 0 run tellraw @s {"rawtext":[{"text":"§l§6[§eError§6]§r AFK isn't compatible with the Speed X Challenge! Disable the Speed X Challenge to make changes."}]}
execute if entity @s[tag=trust_player_control] if score mode timer_settings matches 0..1 if score speed_x timer_addon matches 1 if score lang timer_settings matches 1 run tellraw @s {"rawtext":[{"text":"§l§6[§eError§6]§r AFK ist nicht mit dem Speed Run Mode kompatible! Deaktivieren sie die Speed X Challenge um Änderungen vorzunehmen."}]}
execute if entity @s[tag=trust_player_control] if score mode timer_settings matches 0..1 if score speed_x timer_addon matches 1 if score lang timer_settings matches 2 run tellraw @s {"rawtext":[{"translate":"timeru.header.error"},{"text":" "},{"translate":"timeru.message.incompatible.not_possible", "with":["AFK","Speed X"]}]}
execute if entity @s[tag=trust_player_control] if score mode timer_settings matches 0..1 if score speed_x timer_addon matches 1 run title @a[tag=timer_menu_target] title §eAn Error occurred
execute if entity @s[tag=trust_player_control] if score mode timer_settings matches 0..1 if score speed_x timer_addon matches 1 run title @a[tag=timer_menu_target] subtitle -- Look in the chat --
execute if entity @s[tag=trust_player_control] if score mode timer_settings matches 0..1 if score speed_x timer_addon matches 1 unless score custom_music timer_settings matches 1 run playsound random.pop @s
execute if entity @s[tag=trust_player_control] if score mode timer_settings matches 0..1 if score speed_x timer_addon matches 1 if score custom_music timer_settings matches 1 run playsound timeru.message @s

execute if entity @s[tag=trust_player_control] if score mode timer_settings matches 0..1 if score speed_run timer_settings matches 1 if score lang timer_settings matches 0 run tellraw @s[tag=trust_player_control] {"rawtext":[{"text":"§l§6[§eError§6]§r AFK isn't compatible with the Speed Run Mode! Disable the Speed Run Mode to make changes."}]}
execute if entity @s[tag=trust_player_control] if score mode timer_settings matches 0..1 if score speed_run timer_settings matches 1 if score lang timer_settings matches 1 run tellraw @s[tag=trust_player_control] {"rawtext":[{"text":"§l§6[§eError§6]§r AFK ist nicht mit dem Speed Run Mode kompatible! Deaktivieren sie den Speed Run Mode um Änderungen vorzunehmen."}]}
execute if entity @s[tag=trust_player_control] if score mode timer_settings matches 0..1 if score speed_run timer_settings matches 1 if score lang timer_settings matches 2 run tellraw @s[tag=trust_player_control] {"rawtext":[{"translate":"timeru.header.error"},{"text":" "},{"translate":"timeru.message.incompatible.not_possible", "with":["AFK","Speed Run"]}]}
execute if entity @s[tag=trust_player_control] if score mode timer_settings matches 0..1 if score speed_run timer_settings matches 1 run title @a[tag=timer_menu_target] title §eAn Error occurred
execute if entity @s[tag=trust_player_control] if score mode timer_settings matches 0..1 if score speed_run timer_settings matches 1 run title @a[tag=timer_menu_target] subtitle -- Look in the chat --
execute if entity @s[tag=trust_player_control] if score mode timer_settings matches 0..1 if score speed_run timer_settings matches 1 unless score custom_music timer_settings matches 1 run playsound note.didgeridoo
execute if entity @s[tag=trust_player_control] if score mode timer_settings matches 0..1 if score speed_run timer_settings matches 1 if score custom_music timer_settings matches 1 run playsound timeru.function_no_content

# permissions
execute if entity @s[tag=!trust_player_control] if score lang timer_settings matches 0 run tellraw @s {"rawtext":[{"text":"§l§6[§eError§6]§r You do not have the necessary permissions for this action. Current players who could grant you this permission: §l"},{"selector": "@a[tag=trust_player_control]"}]}
execute if entity @s[tag=!trust_player_control] if score lang timer_settings matches 1 run tellraw @s {"rawtext":[{"text":"§l§6[§eError§6]§r Sie verfügen nicht über die erforderlichen Berechtigungen für diese Aktion. Aktuelle Spieler, die Ihnen diese Erlaubnis erteilen könnten: §l"},{"selector": "@a[tag=trust_player_control]"}]}
execute if entity @s[tag=!trust_player_control] if score lang timer_settings matches 1 run tellraw @s {"rawtext":[{"translate":"timeru.header.error"},{"text":" "},{"translate":"timeru.message.permission.no", "with":[{"rawtext":[{"selector":"@a[tag=trust_player_control]"}]}]}]}
execute if entity @s[tag=!trust_player_control] unless score custom_music timer_settings matches 1 run playsound block.false_permissions
execute if entity @s[tag=!trust_player_control] if score custom_music timer_settings matches 1 run playsound timeru.function_no_permissions @s

# reset state
execute if entity @s[tag=trust_player_control] if score mode timer_settings matches 2 if score lang timer_settings matches 0 run tellraw @s {"rawtext":[{"text":"§l§6[§eError§6]§r This action can only run in the main menu."}]}
execute if entity @s[tag=trust_player_control] if score mode timer_settings matches 2 if score lang timer_settings matches 1 run tellraw @s {"rawtext":[{"text":"§l§6[§eError§6]§r Diese Aktion kann nur im Hauptmenü ausgeführt werden."}]}
execute if entity @s[tag=trust_player_control] if score mode timer_settings matches 2 if score lang timer_settings matches 1 run tellraw @s {"rawtext":[{"translate":"timeru.header.error"},{"text":" "},{"translate":"timeru.message.reset_state.error"}]}
execute if entity @s[tag=trust_player_control] if score mode timer_settings matches 2 run title @a[tag=timer_menu_target] title §eAn Error occurred
execute if entity @s[tag=trust_player_control] if score mode timer_settings matches 2 run title @a[tag=timer_menu_target] subtitle -- Look in the chat --

execute if entity @s[tag=trust_player_control] if score mode timer_settings matches 2 if score reset_type timer_settings matches 2 if score help timer_settings matches 1 if score lang timer_settings matches 0 run tellraw @s[tag=trust_player_control] {"rawtext":[{"text":"§l§6[§eHelp§6]§r Run §g§l/function timer/control§r"}]}
execute if entity @s[tag=trust_player_control] if score mode timer_settings matches 2 if score reset_type timer_settings matches 2 if score help timer_settings matches 1 if score lang timer_settings matches 1 run tellraw @s[tag=trust_player_control] {"rawtext":[{"text":"§l§6[§eHilfe§6]§r Führe §g§l/function timer/control§r aus"}]}
execute if entity @s[tag=trust_player_control] if score mode timer_settings matches 2 if score reset_type timer_settings matches 2 if score help timer_settings matches 1 if score lang timer_settings matches 2 run tellraw @s[tag=trust_player_control] {"rawtext":[{"translate":"timeru.header.help"},{"text":" "},{"translate":"timeru.message.help.run", "with":["/function timer/control"]}]}
execute if entity @s[tag=trust_player_control] if score mode timer_settings matches 2 unless score custom_music timer_settings matches 1 run playsound note.didgeridoo
execute if entity @s[tag=trust_player_control] if score mode timer_settings matches 2 if score custom_music timer_settings matches 1 run playsound timeru.function_no_content


